sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development

branches:
  only:
    - master

env:
    matrix:
    - TARGET=neko,node
    - TARGET=flash,js
    - TARGET=cpp
    - TARGET=cs,java

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib dev hxslam .
  - haxelib git hxmake https://github.com/eliasku/hxmake.git

script:
  - haxelib run hxmake test --override-test-target=${TARGET}