version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

matrix:
  fast_finish: true

branches:
  only:
    - master

install:
  - cinst haxe -version 3.2.1 -y
  - RefreshEnv
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  - haxelib install travix
  - haxelib run travix install
  - haxelib install utest
  - haxelib dev hxslam .

build: off

test_script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix node
  - haxelib run travix flash
  - haxelib run travix java
